build:
	g++ src/main.cpp src/glad.c -o application -I./include -L./lib -lglfw3 -lGL -lX11 -lpthread -lXrandr -lXi -ldl

run: build
	./application

build-ex1:
	g++ src/ex1.cpp src/glad.c -o application -I./include -L./lib -lglfw3 -lGL -lX11 -lpthread -lXrandr -lXi -ldl

run-ex1: build-ex1
	./application

build-ex2:
	g++ src/ex2.cpp src/glad.c -o application -I./include -L./lib -lglfw3 -lGL -lX11 -lpthread -lXrandr -lXi -ldl

run-ex2: build-ex2
	./application

build-ex3:
	g++ src/ex3.cpp src/glad.c -o application -I./include -L./lib -lglfw3 -lGL -lX11 -lpthread -lXrandr -lXi -ldl

run-ex3: build-ex3
	./application

build-1-shader:
	g++ src/1-shader.cpp src/glad.c -o application -I./include -L./lib -lglfw3 -lGL -lX11 -lpthread -lXrandr -lXi -ldl

run-1-shader: build-1-shader
	./application
	
